name: code-examples
version: 1.0.0.0
github: "Sir4ur0n/blog"
license: BSD3
author: "Julien Debon"
maintainer: "julien.debon@decathlon.com"
copyright: "WTFPL"

description: Code examples of my blog <https://sir4ur0n.github.io>

default-extensions:
  - BangPatterns
  - BinaryLiterals
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - DuplicateRecordFields
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedLists
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - TypeSynonymInstances
  - ViewPatterns
  - StrictData

ghc-options:
  - -Wall
  - -Wcompat
  # Some additional compiler warnings from https://medium.com/mercury-bank/enable-all-the-warnings-a0517bc081c3
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wmissing-home-modules
  - -Widentities
  - -Wredundant-constraints
  # Parallel by default
  - -j
  # Don't optimize by default (faster build time)
  - -O0
  # Polysemy for algebraic effects
  - -fplugin=Polysemy.Plugin
  - -flate-specialise
  - -fspecialise-aggressively

dependencies:
  # Basic dependencies
  - base
  - text
  - mtl
  - containers

  # Effect handling
  - polysemy
  - polysemy-plugin

  # Web application
  - servant
  - servant-server
  - wai
  - wai-extra
  - warp

  # JSON support
  - aeson

  # Database
  - sqlite-simple

  # Unit tests
  - HUnit

  # Property-based tests
  - QuickCheck

library:
  source-dirs: src
