# Inspired by https://vllmrt.net/spam/hakyll-github-actions-pages.html
name: Build and deploy to Github pages
on: push

jobs:
  build-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-build
      - run: result/bin/blog build
      - name: 'Deploy to Github pages'
        uses: peaceiris/actions-gh-pages@v3.9.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: _site
          EXTERNAL_REPOSITORY: sir4ur0n/sir4ur0n.github.io
        if: github.ref == 'refs/heads/master'
