# Inspired by https://vllmrt.net/spam/hakyll-github-actions-pages.html
name: Build and deploy to Github pages
on: push

jobs:
  build-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: cachix/install-nix-action@v6
      - run: nix-build
      - run: result/bin/blog build
      - name: 'Run peaceiris/actions-gh-pages@v2.5.0: deploy to Github pages'
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: _site
          EXTERNAL_REPOSITORY: robx/robx.github.io
        if: github.ref == 'refs/heads/master'
